### ISSUE TITLE
Upgrade ioredis

### ISSUE THREAD

**Issue by cavis** [PRX/dovetail-counts-lambda#27]
We're a bit behind on ioredis (4.0.0 -> 4.16.3).  And there are some [good bugfixes](https://github.com/luin/ioredis/blob/master/Changelog.md) related to reconnecting.  May alleviate some of our intermittent `RedisConnError: Failed to refresh slots cache` errors.

There are also some suggestions specifically on Elasticache usage [in this thread](https://github.com/luin/ioredis/issues/711).

**Comment by yunghoy** [comment]
I came here after seeing this text.
Redis: 5.0.6
ioredis: 4.16.2 and 4.16.3
